export const FETCH_SEARCH_CARDS_DATA_REQUEST =
  'FETCH_SEARCH_CARDS_DATA_REQUEST' as const

export const FETCH_SEARCH_CARDS_DATA_SUCCESS =
  'FETCH_SEARCH_CARDS_DATA_SUCCESS' as const

export const FETCH_SEARCH_CARDS_DATA_FAILURE =
  'FETCH_SEARCH_CARDS_DATA_FAILURE' as const

export const FETCH_SEARCH_CARDS_DATA_EMPTY =
  'FETCH_SEARCH_CARDS_DATA_EMPTY' as const
