export const FETCH_ANIME_PAGE_REQUEST = 'FETCH_ANIME_PAGE_REQUEST' as const

export const FETCH_ANIME_PAGE_SUCCESS = 'FETCH_ANIME_PAGE_SUCCESS' as const

export const FETCH_ANIME_PAGE_FAILURE = 'FETCH_ANIME_PAGE_FAILURE' as const

export const FETCH_ANIME_PAGE_EMPTY = 'FETCH_ANIME_PAGE_EMPTY' as const
