export const FETCH_HOME_CARDS_DATA_REQUEST =
  'FETCH_HOME_CARDS_DATA_REQUEST' as const

export const FETCH_HOME_CARDS_DATA_SUCCESS =
  'FETCH_HOME_CARDS_DATA_SUCCESS' as const

export const FETCH_HOME_CARDS_DATA_FAILURE =
  'FETCH_HOME_CARDS_DATA_FAILURE' as const

export const FETCH_HOME_CARDS_DATA_EMPTY =
  'FETCH_HOME_CARDS_DATA_EMPTY' as const

export const CLEAR_HOME_FILTERS = 'CLEAR_HOME_FILTERS' as const

export const SET_GENRE_TO_HOME_FILTERS = 'SET_GENRE_TO_HOME_FILTERS' as const

export const SET_RATING_TO_HOME_FILTERS = 'SET_RATING_TO_HOME_FILTERS' as const
