export const FETCH_LISTS_REQUEST = 'FETCH_LISTS_REQUEST' as const

export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS' as const

export const FETCH_LISTS_FAILURE = 'FETCH_LISTS_FAILURE' as const

export const POST_NEW_LIST_REQUEST = 'POST_NEW_LIST_REQUEST' as const

export const POST_NEW_LIST_SUCCESS = 'POST_NEW_LIST_SUCCESS' as const

export const POST_NEW_LIST_FAILURE = 'POST_NEW_LIST_FAILURE' as const

export const POST_NEW_ITEM_TO_LIST_REQUEST =
  'POST_NEW_ITEM_TO_LIST_REQUEST' as const

export const POST_NEW_ITEM_TO_LIST_SUCCESS =
  'POST_NEW_ITEM_TO_LIST_SUCCESS' as const

export const POST_NEW_ITEM_TO_LIST_FAILURE =
  'POST_NEW_ITEM_TO_LIST_FAILURE' as const

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST' as const

export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS' as const

export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE' as const

export const DELETE_ITEM_FROM_LIST_REQUEST =
  'DELETE_ITEM_FROM_LIST_REQUEST' as const

export const DELETE_ITEM_FROM_LIST_SUCCESS =
  'DELETE_ITEM_FROM_LIST_SUCCESS' as const

export const DELETE_ITEM_FROM_LIST_FAILURE =
  'DELETE_ITEM_FROM_LIST_FAILURE' as const

export const FETCH_LIST_ANIMES_REQUEST = 'FETCH_LIST_ANIMES_REQUEST' as const

export const FETCH_LIST_ANIMES_SUCCESS = 'FETCH_LIST_ANIMES_SUCCESS' as const

export const FETCH_LIST_ANIMES_EMPTY = 'FETCH_LIST_ANIMES_EMPTY' as const

export const FETCH_LIST_ANIMES_FAILURE = 'FETCH_LIST_ANIMES_FAILURE' as const
