export const UPDATE_ANIME_LIST = 'UPDATE_ANIME_LIST'

export const UPDATE_FILTERS = 'UPDATE_FILTERS'

export const SET_MONO_FILTER = 'SET_MONO_FILTER'

export const UPDATE_GENRES_LIST = 'UPDATE_GENRES_LIST'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
