export const UPDATE_FILTERS = 'UPDATE_FILTERS' as const

export const SET_MONO_GENRE = 'SET_MONO_GENRE' as const

export const SET_MONO_RATING = 'SET_MONO_RATING' as const

export const CLEAR_FILTERS = 'CLEAR_FILTERS' as const

export const FETCH_ANIME_REQUEST = 'FETCH_ANIME_REQUEST' as const

export const FETCH_ANIME_SUCCESS = 'FETCH_ANIME_SUCCESS' as const

export const FETCH_ANIME_FAILURE = 'FETCH_ANIME_FAILURE' as const

export const FETCH_ANIME_EMPTY = 'FETCH_ANIME_EMPTY' as const

export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS' as const

export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE' as const

export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST' as const

export const FETCH_ANIME_PAGE_REQUEST = 'FETCH_ANIME_PAGE_REQUEST' as const

export const FETCH_ANIME_PAGE_SUCCESS = 'FETCH_ANIME_PAGE_SUCCESS' as const

export const FETCH_ANIME_PAGE_FAILURE = 'FETCH_ANIME_PAGE_FAILURE' as const

export const FETCH_ANIME_PAGE_EMPTY = 'FETCH_ANIME_PAGE_EMPTY' as const

export const SET_MULTI_FILTERS = 'SET_MULTI_FILTERS' as const

export const CLEAR_MULTI_FILTERS = 'CLEAR_MULTI_FILTERS' as const

export const SET_GENRE_TO_MULTI_FILTERS = 'SET_GENRE_TO_MULTI_FILTERS' as const

export const SET_Q_TO_MULTI_FILTERS = 'SET_Q_TO_MULTI_FILTERS' as const
