export { AnimeByIdPage } from './AnimeByIdPage'
export { HomePage } from './HomePage'
export { ListsPage } from './ListsPage'
export { RandomAnimePage } from './RandomAnimePage'
export { SearchPage } from './SearchPage'
